### PR TITLE
Update README.md: Add quasselclient

### PR DESCRIPTION
**Pull request by dsprenkels**
This pull request adds a link to the new `quasselclient` profile to the readme file under the category "Active profiles".

### CODE REVIEW

**Comment by cryptofuture** [comment]
That was fast!

**Comment by dsprenkels** [comment]
I didn't really predict that #1 would be merged within a day myself, given that the [last commit](https://github.com/cryptofuture/apparmor-profiles/commit/65ef91b0c7c0f9e72ead8335311dba8202701747) had been from December '16. :smile:

**Comment by cryptofuture** [comment]
I just run most software in containers now even on desktop, beside I already well established profiles for most software I use, so it became a lot slower. But yes, you encourage me to make it more active again.

**Comment by dsprenkels** [comment]
I currently see that containers are often used as a mechanism to force mandatory access control over arbitrary executables. But it is so much slower, and the same could be achieved if OS'es and developers would just provide us with the profiles that we need. (I personally use these profiles only for binaries that are closed-source/really old).

Ever seen @NuxiNL's [CloudABI](https://nuxi.nl/cloudabi/)?

**Comment by cryptofuture** [comment]
I use LXD and its nicely integrated with apparmor, and you could run different apparmor rules inside container too, and it could be even faster than host if you specially designed lxd storage for it. Otherwise, speed just the same.
I really like how its done in snap. But sadly most snaps are run with dev privileges, instead of running under apparmor like it was intended. And right now snaps are more useful for tasks like to install newer version of go.
I looked into CloudABI, and I could say most devs just trying to make their application run and work as intended, and it will be hard to redo app for it, so its could considered only if you just started working on your application. So basically right now its quite useless, unless someone will put huge money into it, and start mass opens-source porting/rewriting. More above I pretty sure clang just can't build some software, unless maintainer will be qualified enough to write patches. But writing patches is worst thing you would want, if you want just to build someone software. Even something like adding multiple `/* fall through */` commentary could be not fun at all.

**Pull request merged**
